baseURL = "https://rafikahmh.github.io/"
languageCode = "en-us"
title = "Rafikah Halim"
theme = "hugo-initio"
publishDir = "docs"
relativeURLs = true

[params]
    name = "Rafikah Halim"
    description = "Product + Growth Enthusiast | Hi! I'm Rafikah, and I love digital product design, marketing and data. I've spent a year in a Silicon Valley startup as a product manager, and I've dabbled in growth marketing roles in Uber and Ogilvy & Mather."
    email = "anthony.russel42@example.com"
    phone = "+234 23 9873237"
    address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2017
    background = ""
    favicon = "images/rh-favicon.png"
    DateForm = "January 2, 2006"
    keywords = ["Rafikah Halim" ,"Product Manager", "Growth Hacker"]

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 12

[[menu.main]]
    name = "portfolio"
    url = "/portfolio/"
    weight = 10

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-113213379-1"
