baseURL = "https://rafikahmh.github.io/"
languageCode = "en-us"
title = "Rafikah Halim"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Anthony Russel"
    description = "A mystery person"
    email = "anthony.russel42@example.com"
    phone = "+234 23 9873237"
    address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2017
    background = ""
    favicon = "images/icons8-diamond-50.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 12

[[menu.main]]
    name = "portfolio"
    url = "/portfolio/"
    weight = 10

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-113213379-1"